### ISSUE TITLE
Mermaids are prebuilt in Gnarled Forest

### ISSUE THREAD

**Issue by VipEr-sta** [UchuServer/Uchu#132]
The missions still tell the player to build them, but they are already built.

**Comment by TheNexusAvenger** [comment]
This bug no longer seems to be the case using the latest `dev` branch, but Mermaids still aren't complete. They don't appear to despawn, and the 1 in the middle of the forest that requires a head does not consume the head on. This second part may be a generalized problem where quick builds that require items, like the platforms in Crux Prime and the rebuildable wall in Avant Gardens, don't consume the item.
