### ISSUE TITLE
Rocket building can induce a client crash

### ISSUE THREAD

**Issue by elenawinters** [UchuServer/Uchu#21]
Rocket building can induce a client crash.

Steps to reproduce:
1. Enter building mode.
2. Drag a rocket piece out of your inventory, and place it on the ground.
3. Pick it up with shift. You will notice that nothing will appear in your hands but you will be holding something.
4. Press shift again, so you can interact with buttons.
5. Hit the Exit X that is above the rocket hologram.

The client will crash.

This wont likely be an issue for everyone, as people are likely to drag and drop rocket pieces into the hologram.

**Comment by VaiskiKP** [comment]
[Video showing this happening](https://youtu.be/pmcKJ5GLu_E)

**Comment by Jettford** [comment]
It might need to put the item back in your inventory not too sure, will test on another server later.

**Comment by teccheck** [comment]
This should be fixed in the Modular building PR
