### ISSUE TITLE
Malstrom Mechs constantly "fall" over when playing their shooting animation.

### ISSUE THREAD

**Issue by Bitl** [UchuServer/Uchu#36]

**Comment by Jettford** [comment]
Why is this wontfix @elenawinters

**Comment by TheNexusAvenger** [comment]
I was tinkering around with an unrelated issue a while ago where players would start upside down, and I think I found it was the quaternion (rotation) of the character facing down instead of up. This may be related where we send an upside-down rotation.

**Comment by Jettford** [comment]
I think it is significantly more simple then that, I think this has to do with cursed combat states

**Comment by elenawinters** [comment]
Look in dev chat. I've explained the reason for making it no fix before. Now leave me out of Uchū development.
