### ISSUE TITLE
Achievements for using binoculars and reading plaques do not update.

### ISSUE THREAD

**Issue by jonnylegoboy911** [UchuServer/Uchu#49]
(discovered on Venture Explorer)

**Comment by Jettford** [comment]
Is this in general or just on VE? (Because the binoculars and plaques do not work on VE)

**Comment by jonnylegoboy911** [comment]
> Is this in general or just on VE? (Because the binoculars and plaques do not work on VE)
It was in general when I opened the issue but now I'm able to complete the achievements both in VE and AG.
