### ISSUE TITLE
Mech (when turned into a turret) doesn't attack stromlings

### ISSUE THREAD

**Issue by VaiskiKP** [UchuServer/Uchu#62]
Mech (when turned into a turret) doesn't attack any nearby stromlings.
[Video](https://youtu.be/itcruXHsACE)

**Comment by Jettford** [comment]
This can be fixed using the same AI that the nexus force person uses (Can't remember his name and can't look it up on school wifi 🤦 )

**Comment by MickVermeulen** [comment]
This is probably due to combat AI lag, both on the test server and in local testing this doesn't happen. Closing.
