### ISSUE TITLE
Loading Bar Stuck at 55% at AG

### ISSUE THREAD

**Issue by Harcronium** [UchuServer/Uchu#67]
Some reason, any characters in Avant gardens cannot load in.

**Comment by elenawinters** [comment]
Duplicate of https://github.com/yuwui/Uchu/issues/66

**Comment by MickVermeulen** [comment]
closing as we're keeping track of this in another issue

**Comment by TheNexusAvenger** [comment]
Re-opening because this is still a problem, and I think I found the cause. The cause has been shared privately amongst the developers as this is effectively a denial of service bug that someone can utilize with just a client.

Edit: Probably should have re-opened the other Issue. Oh well.
