### ISSUE TITLE
VE mission "Venture into Knowledge" doesn't work until going to character create and then back

### ISSUE THREAD

**Issue by VaiskiKP** [UchuServer/Uchu#68]
Mission "Venture into Knowledge" (1896) doesn't work until you go to Character Create and back. (Relaunching client also works.)
[Video](https://youtu.be/JivW6X_sgUQ)

**Comment by Jettford** [comment]
Note: This is a issue with the flag mission type and appears to be random when testing

**Comment by MustacheMan2** [comment]
Quite sure this bug never occurs anymore.

**Comment by TheNexusAvenger** [comment]
Haven't seen any reports of this within the past few months. Going to close it due to inactivity and possibly being fixed.
