### ISSUE TITLE
Smashing crates for rocket parts in VE doesn't always work. (After starting mission 308)

### ISSUE THREAD

**Issue by VaiskiKP** [UchuServer/Uchu#69]
Smashing crates for rocket parts in VE doesn't always work (specifically after starting mission 308 ("Not Enough Lifepods?")). Sometimes after picking up a rocket part it doesn't get checked off on the mission. I've got this to happen twice, once with a Cockpit rocket module and once with a Nose Cone rocket module.
[Video](https://youtu.be/pO1wFHc6tVM)

Also at [0:06](https://youtu.be/pO1wFHc6tVM?t=6) in the video you can see issue #53.

**Comment by Jettford** [comment]
I have a feeling that this is just the server struggling to keep up

**Comment by MickVermeulen** [comment]
I'm pretty sure that the game loop performance branch will fix this due to temporarily disabling mission item checks.

**Comment by TheNexusAvenger** [comment]
This should be addressed with one of the performance refactors (pull requests https://github.com/UchuServer/Uchu/pull/140 and https://github.com/UchuServer/Uchu/pull/176).
