### ISSUE TITLE
Foot Race Timer Freezes

### ISSUE THREAD

**Issue by Harcronium** [UchuServer/Uchu#73]
https://gyazo.com/2b6eb5e13647d324cd996c2734aa666e
After you past a couple of the goals, the foot race timer can freeze entirely.

**Comment by MustacheMan2** [comment]
This goes for all foot races, I can assume it simply isn't completed yet.

**Comment by elenawinters** [comment]
Foot races should be mostly client sided.

I'll take a look at this when I get the chance.

**Comment by Jettford** [comment]
Footraces are completely client sided, other then ones with the leader board. @Harcronium could you check if this issue occurs with any other footraces?
