### ISSUE TITLE
Spider Queen Trail Quest from Wisp Lee

### ISSUE THREAD

**Issue by Harcronium** [UchuServer/Uchu#75]
Still doable, just can't see the floating bricks, so instead I had to use the floor to tell where to place the vacuum.

**Comment by Harcronium** [comment]
Actually, was only able to get 1/8 so far.  Might not be doable until that visual error is fixed.

**Comment by Jettford** [comment]
This is a weird issue I have seen occur before, oh and side note about this mission the vacuum needs to be spawned a bit in front of you not in you

**Comment by louisp52** [comment]
I have not run into this issue when running on the Dev Build as of 12 May.

**Comment by TheNexusAvenger** [comment]
Going to close this since it doesn't seem to be an issue at this time. Please reply or re-open the issue if it is on the `dev` branch or later branches.
