### ISSUE TITLE
player is always rendered upside down on world load

### ISSUE THREAD

**Issue by MickVermeulen** [UchuServer/Uchu#84]
When joining a world, during the intro screen, the player is rendered upside down.

**Comment by Jettford** [comment]
Do you have a screenshot of this?

**Comment by NinjaOfLU** [comment]
I don't have a screenshot to hand, but it's really nicely replicated with the port swapping glitch where player position is never updated - in that instance, the player appears to all other players to remain upside down indefinitely on world load.
