### ISSUE TITLE
imagination isn't synced properly on world load

### ISSUE THREAD

**Issue by MickVermeulen** [UchuServer/Uchu#85]
Even though the client shows you how much imagination you should have on world load, the server thinks the client has 0 imagination on world load, leading to a weird visual bug where the UI tells you you have X imagination but when trying to build something you get the popup that you don't have enough imagination. Probably an issue with the world init XML.

**Comment by TheNexusAvenger** [comment]
I haven't seen this issue in a while and I am tempted to close the issue, but I am not sure if anyone else has had this happen recently. Not a lot has been discussed internally about this either.

**Comment by TheNexusAvenger** [comment]
Going to close it for inactivity. If anyone sees this issue again, please comment on this issue.
