### ISSUE TITLE
flag values aren't sent correctly

### ISSUE THREAD

**Issue by MickVermeulen** [UchuServer/Uchu#97]
when picking up a flag (for example the one at spawn in AG) and relogging, the flag reappears. This is probably an issue with the client init XML.

**Comment by Jettford** [comment]
Why do you think it is the XML?

**Comment by MickVermeulen** [comment]
Bc the XML sends the initial values for each collected flag and those apparently aren't correct, otherwise the flags wouldn't appear.

**Comment by Jettford** [comment]
where in the XML?

**Comment by MickVermeulen** [comment]
Here https://github.com/UchuServer/Uchu/blob/0d3c2b1ce68571a888936b1e7be24f58561696c8/Uchu.World/Handlers/WorldInitializationHandler.cs#L345. Note that it's some boolean trickery, should be described in the google docs under the char XML init. What's odd is that, afaik, we implemented this properly but the client isn't loading them properly. Flag tasks do work (which the VE -> AG mission uses), bc traveling from VE to AG completes that first mission. So what might be the case is that the collect heart flag tasks aren't sent properly to the client or aren't sent at all.

**Comment by Jettford** [comment]
Flags are different to collectable flags

**Comment by MickVermeulen** [comment]
Ah yeah, see it in https://docs.google.com/document/d/1XDh_HcXMjSdaGeniG1dND5CA7jOFXIPA_fxCnjvjaO4/edit#heading=h.uq1yc0da2y40 now. Then I'd recommend ensuring that we actually send mission progress regarding the collectible achievements.

**Comment by MickVermeulen** [comment]
Maybe double check if this line is correct: https://github.com/UchuServer/Uchu/blob/0d3c2b1ce68571a888936b1e7be24f58561696c8/Uchu.World/Handlers/WorldInitializationHandler.cs#L427.

**Comment by TheNexusAvenger** [comment]
I am guessing this isn't an issue anymore. I have not noticed this in a very long time, and the initial reported issue isn't an issue anymore. Anyone is free to reply or re-open this issue if it is still a problem.
